### PR TITLE
Added a Few more Colors to choos from

### PR DESCRIPTION
**Pull request by tobiasreichel**
Maybe I exaggerated a bit

but better more to choose form 

if not just yeet the pr

### CODE REVIEW

**Comment by Mirasaki** [comment]
@tobiasreichel Why did you close this?

**Comment by tobiasreichel** [comment]
To many errors and typos will make a clean one in just a bit

**Comment by Mirasaki** [comment]
Alrighty, I see - that's all fine though, I always run PR's through the automatic linter and make any required changes/additions

**Comment by tobiasreichel** [comment]
If you don't have a problem then please open it again ☺️☺️

**Comment by Mirasaki** [comment]
This un-does changes I made to the last PR, you should update your codebase to the latest version
I've replicated the PR in #59

**Pull request closed without merging**
